### ISSUE TITLE
Using %NULL does not link to the GLib NULL define

### ISSUE THREAD

**Issue by thiblahute** [MathieuDuponchelle/hotdoc#27] opened 2015-10-10 14:26 UTC
In my  [hotodoc branch for GES](https://git.collabora.com/cgit/user/tsaunier/gst-editing-service/.git/log/?h=hotdoc) in docs/ges/html/c/GESTimeline.html#ges_timeline_new_audio_video I can see:

```
error: An error to be set in case something wrong happens or %NULL
```

we should not see %NULL but have a like to https://developer.gnome.org/glib/unstable/glib-Standard-Macros.html#NULL:CAPS

**Comment by MathieuDuponchelle** [comment] 2015-10-10 16:23
:+1:

**Comment by MathieuDuponchelle** [comment] 2015-10-10 16:23
You've got a like now

**Comment by MathieuDuponchelle** [comment] 2015-10-10 16:24
Also this is the github for hotdoc, hotodoc sounds like a promising project though

**Comment by MathieuDuponchelle** [comment] 2015-10-10 16:41
By the way closing bug because I can't reproduce, after discussion glib/index.sgml was absent on that system for some reason.

**Closed** 2015-10-10 16:41 UTC
Labels: hotodoc, invalid
