### ISSUE TITLE
Links to enum values are not link when using the `#` notation

### ISSUE THREAD

**Issue by thiblahute** [MathieuDuponchelle/hotdoc#22] opened 2015-10-03 07:29 UTC
In my  [hotodoc branch for GES](https://git.collabora.com/cgit/user/tsaunier/gst-editing-service/.git/log/?h=hotdoc) in `docs/ges/html/c//GESTimeline.html#ges_timeline_commit` the links to `GST_STATE_READY` and friend are not created:

```
The GESTimeline::commited signal will be emitted when the (possibly updated) GstPipeline is ready to output data again, except if the state of the timeline was #GST_STATE_READY or #GST_STATE_NULL.

Note that all the pending changes will automatically be executed when the timeline goes from #GST_STATE_READY to #GST_STATE_PAUSED, which usually is triggered by corresponding state changes in a containing GESPipeline.
```

**Comment by MathieuDuponchelle** [comment] 2015-10-05 19:16
I checked and the  bug exists with gtk-doc as well, see http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer-editing-services/html/GESTimeline.html#ges-timeline-commit , the cause for this is if you check /usr/share/gtk-doc/html/gstreamer-1.0/index.sgml you will see no mention of GST-STATE-READY:CAPS . That's pretty much a case of NOTOURBUG , closing :/

**Closed by MathieuDuponchelle** 2015-10-05 19:16 UTC
Labels: wontfix
